FROM microsoft/vsts-agent:ubuntu-16.04-docker-17.12.0-ce-standard

RUN apt-get update
RUN apt-get install -y python-setuptools
RUN apt-get clean
RUN pip install --upgrade pip
RUN pip install awscli --upgrade
